Load classpath in windows
cyrilou242/jnotebook pull request #20
Opened 2023-11-07 22:36 UTC by L-marwan

Implemented loading the maven classpath for windows: 

- added the necessary windows command 
- added some handling for the partial error case : when we run the mvn command to get the classpaths, there's a case when some dependency fails to download, or some module fails to build, however, we get some of the classpath, I just assumed that we can load the succeful part, and log a wrning with the error, if you want this to behave differently feel free to let me know and I'll change it. here's a screenshot for this case : 

![image](https://github.com/cyrilou242/jnotebook/assets/5917134/fe0417b1-91aa-4ac9-bc42-f67682c32189)

2023-11-08 13:06 UTC, cyrilou242 commented
very cool thanks! 

> added some handling for the partial error case : when we run the mvn command to get the classpaths, there's a case when some dependency fails to download, or some module fails to build, however, we get some of the classpath, I just assumed that we can load the succeful part, and log a wrning with the error, if you want this to behave differently feel free to let me know and I'll change it. here's a screenshot for this case :

Let's throw if the exit code of the maven command is not zero. Silent/partial fails tend to be confusing.

2023-11-08 20:56 UTC, L-marwan commented
changed behavior to throw in the case where there are errors in the mvn result.

2023-11-08 22:02 UTC, cyrilou242 requested changes

2023-11-08 22:02 UTC, cyrilou242 commented on jnotebook-core/src/main/java/tech/catheu/jnotebook/jshell/ShellProvider.java
> +    final List<String> errors = classpaths.stream().filter(s -> s.startsWith("[ERROR]")).toList();
let's use the exit code of the process directly, it'll be more solid.

You can check
```
pr.exitValue()
```
just after `pr.waitFor()`

If the exit value is not zero, then the process failed and you can throw the RunTimeException.
Also, let's return the full output in this case.

2023-11-08 22:02 UTC, cyrilou242 commented on jnotebook-core/src/main/java/tech/catheu/jnotebook/jshell/ShellProvider.java
> +    final List<String> errors = classpaths.stream().filter(s -> s.startsWith("[ERROR]")).toList();
and maybe add the input command. Such that the user can debug easily.

2023-11-08 22:02 UTC, cyrilou242 commented on jnotebook-core/src/main/java/tech/catheu/jnotebook/jshell/ShellProvider.java
> +  // We need to escape the '.' in the command otherwise it fails
let's remove this comment.

2023-11-09 21:11 UTC, cyrilou242 approved these changes
LGTM thanks!

2023-11-09 21:11 UTC, merged